# Generated by Django 4.1.1 on 2022-10-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dog_bio_alter_dog_img_health'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Health',
        ),
    ]
