# Generated by Django 4.1.1 on 2022-10-05 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_delete_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=30)),
                ('year_recognized', models.IntegerField(max_length=4)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='main_app.dog')),
            ],
        ),
    ]
