# Generated by Django 4.1.1 on 2022-10-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='year_recognized',
            field=models.IntegerField(default=0),
        ),
    ]
