# Generated by Django 4.1.1 on 2022-10-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_history_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('dogs', models.ManyToManyField(to='main_app.dog')),
            ],
        ),
    ]
