# Generated by Django 4.1.1 on 2022-10-05 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_addinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddInfo',
            new_name='Info',
        ),
    ]
