# Generated by Django 4.1.1 on 2022-10-05 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_addinfo_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Info',
            new_name='Size',
        ),
    ]
